# Production environment override
services:
  php:
    build:
      context: .
      target: php_prod
    environment:
      APP_SECRET: ${APP_SECRET}

  nginx:
    build:
      context: .
      target: nginx_prod
